const balise = {
	new: {
		cursor: "pointer",
		display: "inline-flex",
		flexDirection: "row",
		gap: 0,
		borderRadius: 1000,
		backgroundColor: "#EB57571A",
		alignItems: "center",
		padding: "0px 14px",
		justifyContent: "center",
		color: "#EB5757",
		fontWeight: 700,
		fontSize: 10,
		height:30,
		maxWidth:'fit-content'
	},
	accent:{
		cursor: "pointer",
		display: "inline-flex",
		flexDirection: "row",
		gap: 0,
		borderRadius: 1000,
		backgroundColor: "var(--accent-color)",
		alignItems: "center",
		padding: "0px 14px",
		justifyContent: "center",
		color: "white",
		fontWeight: 700,
		fontSize: 10,
		height:30,
		maxWidth:'fit-content'
	},
	grey: {
		cursor: "pointer",
		display: "inline-flex",
		flexDirection: "row",
		gap: 0,
		borderRadius: 1000,
		backgroundColor: "#BDBDBD",
		alignItems: "center",
		padding: "0px 14px",
		justifyContent: "center",
		color: "var(--tags-black-color)",
		fontWeight: 700,
		fontSize: 10,
		height:30,
		maxWidth:'fit-content'
	},
	warning: {
		cursor: "pointer",
		display: "inline-flex",
		flexDirection: "row",
		gap: 0,
		borderRadius: 1000,
		backgroundColor: "rgb(66, 152, 153)",
		alignItems: "center",
		padding: "0px 14px",
		justifyContent: "center",
		color: "#FFF",
		fontWeight: 700,
		fontSize: 10,
		height:30,
		maxWidth:'fit-content'
	},
	success: {
		cursor: "pointer",
		display: "inline-flex",
		flexDirection: "row",
		gap: 0,
		borderRadius: 1000,
		backgroundColor: "var(--accent-color)",
		alignItems: "center",
		padding: "0px 14px",
		justifyContent: "center",
		color: "var(--white)",
		fontWeight: 700,
		fontSize: 10,
		height:30,
		maxWidth:'fit-content'
	},
	blue: {
		cursor: "pointer",
		display: "inline-flex",
		flexDirection: "row",
		gap: 0,
		borderRadius: 1000,
		backgroundColor: "blue",
		alignItems: "center",
		padding: "0px 14px",
		justifyContent: "center",
		color: "var(--white)",
		fontWeight: 700,
		fontSize: 10,
		height:30,
		maxWidth:'fit-content'
	},
	active: {
		cursor: "pointer",
		display: "inline-flex",
		flexDirection: "row",
		gap: 0,
		borderRadius: 1000,
		backgroundColor: "var(--color-1)",
		alignItems: "center",
		padding: "0px 14px",
		justifyContent: "center",
		color: "var(--white)",
		fontWeight: 700,
		fontSize: 10,
		height:30,
		maxWidth:'fit-content'
	},
	border: {
		cursor: "pointer",
		display: "inline-flex",
		flexDirection: "row",
		gap: 0,
		borderRadius: 1000,
		backgroundColor: "var(--color-3)",
		border: "1px solid #d9d9d9",
		alignItems: "center",
		padding: "0px 14px",
		justifyContent: "center",
		color: "var(--tags-black-color)",
		fontWeight: 700,
		fontSize: 10,
		height:30,
		maxWidth:'fit-content'
	},
	simple: {
		cursor: "pointer",
		display: "inline-flex",
		flexDirection: "row",
		gap: 0,
		borderRadius: 1000,
		backgroundColor: "transparent",
		alignItems: "center",
		padding: "0px 14px",
		justifyContent: "center",
		color: "var(--tags-black-color)",
		fontWeight: 700,
		border:"1px solid var(--tags-black-color)",
		fontSize: 10,
		height:30,
		maxWidth:'fit-content'
	},
	dark: {
		cursor: "pointer",
		display: "inline-flex",
		flexDirection: "row",
		gap: 0,
		borderRadius: 1000,
		backgroundColor: "#333",
		alignItems: "center",
		padding: "0px 14px",
		justifyContent: "center",
		color: "white",
		fontWeight: 700,
		fontSize: 10,
		height:30,
		maxWidth:'fit-content'
	},
	red:{
		cursor: "pointer",
		display: "inline-flex",
		flexDirection: "row",
		gap: 0,
		borderRadius: 1000,
		backgroundColor: "red",
		color: "white",
		alignItems: "center",
		padding: "0px 14px",
		justifyContent: "center",
		fontWeight: 700,
		fontSize: 10,
		height:30,
		maxWidth:'fit-content'
	},
	white: {
		cursor: "pointer",
		display: "inline-flex",
		flexDirection: "row",
		gap: 0,
		borderRadius: 1000,
		backgroundColor: "var(--white)",
		alignItems: "center",
		padding: "0px 14px",
		justifyContent: "center",
		fontWeight: 700,
		fontSize: 10,
		height:30,
		maxWidth:'fit-content'
	},
	normal: {
		cursor: "pointer",
		display: "inline-flex",
		flexDirection: "row",
		gap: 0,
		borderRadius: 1000,
		backgroundColor: "var(--white)",
		alignItems: "center",
		padding: "0px 14px",
		justifyContent: "center",
		fontWeight: 500,
		fontSize: 10,
		height:30,
		maxWidth:'fit-content'
	},
	current: {
		cursor: "pointer",
		display: "inline-flex",
		flexDirection: "row",
		gap: 0,
		borderRadius: 1000,
		color: "#3b3b3b",
		backgroundColor: "rgb(225, 225, 225)",
		alignItems: "center",
		padding: "0px 14px",
		justifyContent: "center",
		fontWeight: 500,
		fontSize: 10,
		height:30,
		maxWidth:'fit-content'
	},
	froly: {
		cursor: "pointer",
		display: "inline-flex",
		flexDirection: "row",
		gap: 0,
		borderRadius: 1000,
		backgroundColor: "#eb6060",
		color: "var(--white)",
		alignItems: "center",
		padding: "0px 14px",
		justifyContent: "center",
		fontWeight: 500,
		fontSize: 10,
		height:30,
		maxWidth:'fit-content'
	},
	cornflower_Blue: {
		cursor: "pointer",
		display: "inline-flex",
		flexDirection: "row",
		gap: 0,
		borderRadius: 1000,
		backgroundColor: "#6197eb",
		color: "var(--white)",
		alignItems: "center",
		padding: "0px 14px",
		justifyContent: "center",
		fontWeight: 500,
		fontSize: 10,
		height:30,
		maxWidth:'fit-content'
	},
	medium_Purple: {
		cursor: "pointer",
		display: "inline-flex",
		flexDirection: "row",
		gap: 0,
		borderRadius: 1000,
		backgroundColor: "#a661eb",
		color: "var(--white)",
		alignItems: "center",
		padding: "0px 14px",
		justifyContent: "center",
		fontWeight: 500,
		fontSize: 10,
		height:30,
		maxWidth:'fit-content'
	},
	badge : {
		color:"#333",
		fontWeight: "bold",
		padding:"6px",
		height:30,
		borderRadius: 1000,
	}
}

export {
	balise,
}