spring.datasource.platform=h2
spring.datasource.url=jdbc:h2:${project.basedir}/target/localDb/${artifactId}-h2-schema;AUTO_SERVER=TRUE;MODE=PostgreSQL;NON_KEYWORDS=KEY,VALUE,GROUP
spring.datasource.username=sa
spring.datasource.password=

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.tomcat.initial-size=15
spring.datasource.tomcat.max-wait=30000
spring.datasource.tomcat.max-active=25
spring.datasource.tomcat.default-auto-commit=false

spring.profiles.active=dev

spring.jpa.show-sql=false
spring.jpa.database=h2
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
